dataset: ruler
data_dir: 4096
model: /aifs4su/guhao/Models/Llama-3.1-8B-Instruct
device: cuda:0
press_name: kvzip
compression_ratio: 0.0
key_channel_compression_ratio: null
samples: null
fraction: 0.01
max_new_tokens: null
max_context_length: null
compress_questions: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_dump
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command: KVzipPress(compression_ratio=0.0, layerwise=False, n_sink=4)
seed: 42
kv_cache_nbits: null
kv_cache_backend: quanto
