dataset: math500
data_dir: true
model: /aifs4su/guhao/Models/DeepSeek-R1-Distill-Qwen-1.5B
device: cuda:1
press_name: decoding_streaming_llm
compression_ratio: 0.5
key_channel_compression_ratio: null
samples: 20
fraction: 1.0
max_new_tokens: null
max_context_length: null
compress_questions: false
needle_depth: null
compression_interval: 128
target_size: 256
hidden_states_buffer_size: 128
output_dir: ./results_math
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command: DecodingPress(base_press=StreamingLLMPress(compression_ratio=0.0,
  n_sink=4), compression_interval=128, target_size=256, hidden_states_buffer_size=128)
seed: 42
