dataset: ruler
data_dir: 4096
model: /aifs4su/guhao/checkpoints/llama31_8b_gated_distill_cr50
device: cuda:0
press_name: gated_local128
compression_ratio: 0.6
key_channel_compression_ratio: 0.6
samples: null
fraction: 0.1
max_new_tokens: null
max_context_length: null
compress_questions: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_fra0.1
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
  device_map: cuda:0
press_init_command: GatedPress(gate_mode='dynamic', static_separate_kv=True, gate_type='elementwise',
  init='open', init_open_p=0.999, bias=True, record_mse=False, mse_detach_target=True,
  mse_reduction='token_mean', aux_fp32=True, reg_type='group_lasso', gate_sparsity_threshold=0.5,
  key_channel_compression_ratio=0.6, window_size=128, pairwise_prune=True, sync_kv_prune=True,
  qk_scale_correction=True, _warned_channel_prune_unsupported=False, capture_mode='gated',
  apply_kv_gate=True, record_gate_stats=False, train_gate_mode='soft')
seed: 42
