dataset: math500
data_dir: '4096'
model: /aifs4su/guhao/Models/DeepSeek-R1-Distill-Qwen-1.5B
device: cuda:0
press_name: decoding_h2o
compression_ratio: 0.5
key_channel_compression_ratio: null
samples: 20
fraction: 1.0
max_new_tokens: 8192
max_context_length: null
compress_questions: false
needle_depth: null
compression_interval: 128
target_size: 512
hidden_states_buffer_size: 128
output_dir: ./results_math_target_size_512
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command: H2OPress(compression_ratio=0.5, budget=128, window_size=1, compression_interval=1,
  record_kept_token_indices=False, evicted_token_num=0, decode_step=0)
seed: 42
