dataset: ruler
data_dir: 4096
model: /aifs4su/guhao/Models/Llama-3.1-8B-Instruct
device: cuda:0
press_name: fixed_EA_layer19
compression_ratio: 0.5
key_channel_compression_ratio: null
samples: null
fraction: 0.1
max_new_tokens: null
max_context_length: null
compress_questions: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_fixed_ea_layers
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command: FixedLayerScoreEvictPress(press=ExpectedAttentionPress(compression_ratio=0.5,
  mean_head=False, layer_running_mean=False, running_mean_start_layer=0, n_future_positions=512,
  n_sink=4, use_covariance=True, use_vnorm=True, epsilon=0.0), score_layer_idx=19)
seed: 42
