dataset: ruler
data_dir: 4096
model: /aifs4su/guhao/checkpoints/llama3-1b-instruct-learned-score_future_query
device: cuda:0
press_name: learned_score
compression_ratio: 0.1
key_channel_compression_ratio: null
fraction: 1.0
max_new_tokens: null
max_context_length: null
compress_questions: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_comparison
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
  device_map: cuda:0
press_init_command: LearnedScorePress(compression_ratio=0.1, scorer_attr='learnable_kv_scorer',
  use_vnorm=False, n_sink=4, _initialized=False)
seed: 42
